name: Create issue on commit

on:

  push:
  workflow_dispatch:

jobs:

  build-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Build tutorials
      run: |
        zip -r /tmp/qml_demos.zip data/dev/demos

    - uses: actions/upload-artifact@v2
      with:
        name: built-website-dev
        path: |
          /tmp/qml_demos.zip

  download-artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v2
      with:
        name: built-website-dev

    - name: Display structure of downloaded files
      run: ls -R
