name: Create issue on commit

on:

  push:
  workflow_dispatch:

jobs:

  build-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Display structure of downloaded files
      run: ls -la

    - uses: actions/upload-artifact@v2
      with:
        name: built-website-dev
        path: |
          dev.zip

  build-master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master

    - name: Display structure of downloaded files
      run: ls -la

    - uses: actions/upload-artifact@v2
      with:
        name: built-website-master
        path: |
          master.zip

  check-diffs:
    runs-on: ubuntu-latest
    needs: [build-dev, build-master]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: demo_checker

    - name: Create dev dir
      run: mkdir /tmp/dev/

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: /tmp/dev/

    - uses: actions/download-artifact@v2
      with:
        name: built-website-dev
        path: /tmp/dev/

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: /tmp/dev/

    - name: Unzip dev demos
      run: unzip /tmp/dev/built-website-dev -d /tmp/dev/

    - name: Create master dir
      run: mkdir /tmp/master/

    - uses: actions/download-artifact@v2
      with:
        name: built-website-master
        path: /tmp/master/

    - name: Unzip master demos
      run: unzip /tmp/dev/built-website-master -d /tmp/master/

    - name: Display structure of downloaded files
      run: ls -la /tmp/

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Display structure of downloaded files
      run: |
        git config user.name "QML demo checker Bot"
        git config user.email "<>"

        pip install pytz
        python ./generate_diffs.py
        git add diffs.md
        git commit -m "Update diffs found"
        git push

    - uses: actions/upload-artifact@v2
      with:
        name: diffs
        path: |
          diffs.md
